/*
 * JS for xxx generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'b572e3eb-742e-4282-8fcc-ec2f1e9e6ff1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "xxx",
    "location": "xxx.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}];

xxx_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilecollapsibleset_42': 'xxx_mobilecollapsibleset_42',
        'mobilecollapsblock_43': 'xxx_mobilecollapsblock_43',
        'mobilecollapsblockheader_44': 'xxx_mobilecollapsblockheader_44',
        'mobilecollapsblockcontent_45': 'xxx_mobilecollapsblockcontent_45',
        'mobilecollapsblock_80': 'xxx_mobilecollapsblock_80',
        'mobilecollapsblockheader_81': 'xxx_mobilecollapsblockheader_81',
        'mobilecollapsblockcontent_82': 'xxx_mobilecollapsblockcontent_82',
        'mobilecollapsblock_77': 'xxx_mobilecollapsblock_77',
        'mobilecollapsblockheader_78': 'xxx_mobilecollapsblockheader_78',
        'mobilecollapsblockcontent_79': 'xxx_mobilecollapsblockcontent_79',
        'mobilecollapsblock_206': 'xxx_mobilecollapsblock_206',
        'mobilecollapsblockheader_207': 'xxx_mobilecollapsblockheader_207',
        'mobilecollapsblockcontent_208': 'xxx_mobilecollapsblockcontent_208',
        'mobilecollapsblock_68': 'xxx_mobilecollapsblock_68',
        'mobilecollapsblockheader_69': 'xxx_mobilecollapsblockheader_69',
        'mobilecollapsblockcontent_70': 'xxx_mobilecollapsblockcontent_70',
        'mobilecollapsblock_74': 'xxx_mobilecollapsblock_74',
        'mobilecollapsblockheader_75': 'xxx_mobilecollapsblockheader_75',
        'mobilecollapsblockcontent_76': 'xxx_mobilecollapsblockcontent_76',
        'mobilecollapsblock_46': 'xxx_mobilecollapsblock_46',
        'mobilecollapsblockheader_47': 'xxx_mobilecollapsblockheader_47',
        'mobilecollapsblockcontent_48': 'xxx_mobilecollapsblockcontent_48',
        'mobilecollapsblock_49': 'xxx_mobilecollapsblock_49',
        'mobilecollapsblockheader_50': 'xxx_mobilecollapsblockheader_50',
        'mobilecollapsblockcontent_51': 'xxx_mobilecollapsblockcontent_51'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'xxx';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var xxx_beforeshow = function() {
            Apperyio.CurrentScreen = "xxx";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var xxx_onLoad = function() {
            xxx_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            xxx_deviceEvents();
            xxx_windowEvents();
            xxx_elementsEvents();
        };

    // screen window events
    var xxx_windowEvents = function() {

            $('#xxx').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var xxx_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var xxx_elementsExtraJS = function() {
            // screen (xxx) extra code

            /* mobilecollapsblock_43 */

            $("#xxx_mobilecollapsblock_43 .ui-collapsible-heading-toggle").attr("tabindex", "11");

            /* mobilecollapsblock_80 */

            $("#xxx_mobilecollapsblock_80 .ui-collapsible-heading-toggle").attr("tabindex", "11");

            /* mobilecollapsblock_77 */

            $("#xxx_mobilecollapsblock_77 .ui-collapsible-heading-toggle").attr("tabindex", "11");

            /* mobilecollapsblock_206 */

            $("#xxx_mobilecollapsblock_206 .ui-collapsible-heading-toggle").attr("tabindex", "11");

            /* mobilecollapsblock_68 */

            $("#xxx_mobilecollapsblock_68 .ui-collapsible-heading-toggle").attr("tabindex", "11");

            /* mobilecollapsblock_74 */

            $("#xxx_mobilecollapsblock_74 .ui-collapsible-heading-toggle").attr("tabindex", "14");

            /* mobilecollapsblock_46 */

            $("#xxx_mobilecollapsblock_46 .ui-collapsible-heading-toggle").attr("tabindex", "11");

            /* mobilecollapsblock_49 */

            $("#xxx_mobilecollapsblock_49 .ui-collapsible-heading-toggle").attr("tabindex", "11");

        };

    // screen elements handler
    var xxx_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("collapsibleexpand", '#xxx_mobilecontainer [name="mobilecollapsblock_43"]').on({
                collapsibleexpand: function() {
                    toggle('xxx_mobilecollapsblock_206', 'mob', 'true');
                },
            }, '#xxx_mobilecontainer [name="mobilecollapsblock_43"]');

        };

    $(document).off("pagebeforeshow", "#xxx").on("pagebeforeshow", "#xxx", function(event, ui) {
        xxx_beforeshow();
    });

    if (runBeforeShow) {
        xxx_beforeshow();
    } else {
        xxx_onLoad();
    }
};

$(document).off("pagecreate", "#xxx").on("pagecreate", "#xxx", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    xxx_js();
});